import Head from "next/head";
import Container from "@mui/material/Container";
import { TextField, Button, Box, Avatar } from "@mui/material";
import Logo from "../assets/img/iconQuick.png";
import useSWR from "swr";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [serviceId, setServiceId] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          minHeight="100vh"
        >
          <div className="w-96 bg-gray-500 px-6 py-8 rounded-lg">
            <Avatar className="mx-auto" src={"/src/assets/img/iconQuick.png"} />
            <div className="text-xl mb-2 mx-auto">Bienvenido</div>
            <div className="text-sm mb-2 mx-auto">
              Sigue tus envios con la orden de transporte
            </div>
            <div className="my-4">
              <div className="text-sm mb-2 mx-auto">Buscar servicio</div>
              <TextField
                className="w-full"
                label="Orden de transporte"
                variant="filled"
                onChange={(e) => setServiceId(e.target.value)}
              />
            </div>
            <div className="mt-6">
              <Link href={`/search/${serviceId}`}>
                <Button className="w-full h-14" variant="contained">
                  Buscar servicio
                </Button>
              </Link>
              <Link href={`/map`}>
                <Button className="w-full h-14" variant="contained">
                 Mapa
                </Button>
              </Link>
            </div>
          </div>
        </Box>
      </Container>
    </>
  );
}
