import Head from "next/head";
import Input from "@/components/Input";
import styles from "@/styles/Home.module.css";
import Container from "@mui/material/Container";
import { TextField, Button, Box, Grid } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          minHeight="100vh"
        >
          <div className="w-96 bg-gray-400 rounded px-6 py-8">
            <div className="text-xl mb-2 mx-auto">Bienvenido</div>
            <div className="text-sm mb-2 mx-auto">
              Sigue tus envios con la orden de transporte
            </div>
            <div className="my-4">
              <div className="text-sm mb-2 mx-auto">Buscar servicio</div>
              <TextField
                className="w-full"
                label="Orden de transporte"
                variant="filled"
              />
            </div>
            <div className="mt-6">
              <Button
                className="w-full h-14"
                variant="contained"
              >
                Buscar servicio
              </Button>
            </div>
          </div>
        </Box>
      </Container>
    </>
  );
}
