import Head from "next/head";
import Container from "@mui/material/Container";
import { TextField, Button, Box } from "@mui/material";
import { useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const [serviceId, setServiceId] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          minHeight="100vh"
        >
          <div className="w-96 bg-white p-5 shadow-2xl">
            <div className="w-64 mx-auto py-4">
              <h1 className="text-center font-bold text-2xl mb-4 ">
                Bienvenido
              </h1>
              <div className="text-center text-sm mb-4">
                Sigue tus envios con la orden de transporte
              </div>
            </div>
            <div className="my-4">
              <TextField
                className="w-full"
                label="Orden de transporte"
                variant="filled"
                onChange={(e) => setServiceId(e.target.value)}
              />
            </div>
            <div className="mt-6">
              <Link href={serviceId === "" ? `/` : `/search/${serviceId}`}>
                <Button
                  disabled={serviceId === ""}
                  className="w-full h-14"
                  variant="contained"
                >
                  Buscar servicio
                </Button>
              </Link>
            </div>
          </div>
        </Box>
      </Container>
    </>
  );
}
